// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/profile/v1/profile.proto

package profilev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Traits        map[string]string      `protobuf:"bytes,2,rep,name=traits,proto3" json:"traits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAtUnix int64                  `protobuf:"varint,3,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Profile) GetTraits() map[string]string {
	if x != nil {
		return x.Traits
	}
	return nil
}

func (x *Profile) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type UpsertProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Traits        map[string]string      `protobuf:"bytes,2,rep,name=traits,proto3" json:"traits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProfileRequest) Reset() {
	*x = UpsertProfileRequest{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProfileRequest) ProtoMessage() {}

func (x *UpsertProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProfileRequest.ProtoReflect.Descriptor instead.
func (*UpsertProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertProfileRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpsertProfileRequest) GetTraits() map[string]string {
	if x != nil {
		return x.Traits
	}
	return nil
}

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId     string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	OccurredAtUnix int64                  `protobuf:"varint,4,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

var File_proto_profile_v1_profile_proto protoreflect.FileDescriptor

const file_proto_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/profile/v1/profile.proto\x12\n" +
	"profile.v1\"\xc6\x01\n" +
	"\aProfile\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x127\n" +
	"\x06traits\x18\x02 \x03(\v2\x1f.profile.v1.Profile.TraitsEntryR\x06traits\x12&\n" +
	"\x0fupdated_at_unix\x18\x03 \x01(\x03R\rupdatedAtUnix\x1a9\n" +
	"\vTraitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x11GetProfileRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"\xb8\x01\n" +
	"\x14UpsertProfileRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12D\n" +
	"\x06traits\x18\x02 \x03(\v2,.profile.v1.UpsertProfileRequest.TraitsEntryR\x06traits\x1a9\n" +
	"\vTraitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12(\n" +
	"\x10occurred_at_unix\x18\x04 \x01(\x03R\x0eoccurredAtUnix\"4\n" +
	"\x11ListEventsRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId2\xdc\x01\n" +
	"\x0eProfileService\x12@\n" +
	"\n" +
	"GetProfile\x12\x1d.profile.v1.GetProfileRequest\x1a\x13.profile.v1.Profile\x12F\n" +
	"\rUpsertProfile\x12 .profile.v1.UpsertProfileRequest\x1a\x13.profile.v1.Profile\x12@\n" +
	"\n" +
	"ListEvents\x12\x1d.profile.v1.ListEventsRequest\x1a\x11.profile.v1.Event0\x01B$Z\"cxm/m05/proto/profile/v1;profilev1b\x06proto3"

var (
	file_proto_profile_v1_profile_proto_rawDescOnce sync.Once
	file_proto_profile_v1_profile_proto_rawDescData []byte
)

func file_proto_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_proto_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_proto_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_v1_profile_proto_rawDesc), len(file_proto_profile_v1_profile_proto_rawDesc)))
	})
	return file_proto_profile_v1_profile_proto_rawDescData
}

var file_proto_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_profile_v1_profile_proto_goTypes = []any{
	(*Profile)(nil),              // 0: profile.v1.Profile
	(*GetProfileRequest)(nil),    // 1: profile.v1.GetProfileRequest
	(*UpsertProfileRequest)(nil), // 2: profile.v1.UpsertProfileRequest
	(*Event)(nil),                // 3: profile.v1.Event
	(*ListEventsRequest)(nil),    // 4: profile.v1.ListEventsRequest
	nil,                          // 5: profile.v1.Profile.TraitsEntry
	nil,                          // 6: profile.v1.UpsertProfileRequest.TraitsEntry
}
var file_proto_profile_v1_profile_proto_depIdxs = []int32{
	5, // 0: profile.v1.Profile.traits:type_name -> profile.v1.Profile.TraitsEntry
	6, // 1: profile.v1.UpsertProfileRequest.traits:type_name -> profile.v1.UpsertProfileRequest.TraitsEntry
	1, // 2: profile.v1.ProfileService.GetProfile:input_type -> profile.v1.GetProfileRequest
	2, // 3: profile.v1.ProfileService.UpsertProfile:input_type -> profile.v1.UpsertProfileRequest
	4, // 4: profile.v1.ProfileService.ListEvents:input_type -> profile.v1.ListEventsRequest
	0, // 5: profile.v1.ProfileService.GetProfile:output_type -> profile.v1.Profile
	0, // 6: profile.v1.ProfileService.UpsertProfile:output_type -> profile.v1.Profile
	3, // 7: profile.v1.ProfileService.ListEvents:output_type -> profile.v1.Event
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_profile_v1_profile_proto_init() }
func file_proto_profile_v1_profile_proto_init() {
	if File_proto_profile_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_v1_profile_proto_rawDesc), len(file_proto_profile_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_proto_profile_v1_profile_proto_depIdxs,
		MessageInfos:      file_proto_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_proto_profile_v1_profile_proto = out.File
	file_proto_profile_v1_profile_proto_goTypes = nil
	file_proto_profile_v1_profile_proto_depIdxs = nil
}
